export const ApiParamKey = {
    page_id: 'page_id',
    page_slug: 'page_slug',
    get_section: 'get_section',
    keyword: 'keyword',
    project_slug: 'project_slug',
    orderby: 'orderby',
    order: 'order',
    parent_id: 'parent_id',
    page_no: 'page_no',
    per_page: 'per_page',
    parent_type: 'parent_type',
    field_type: 'field_type',
    field_value: 'field_value',
    gallery: 'gallery',
};
